'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import type { snapshot } from '../../server/data';
import {safeCsv} from '../../server/domain';
import './admin.css';
type Data=Awaited<ReturnType<typeof snapshot>>;
const sections=[['resumen','Resumen','◫'],['inscripciones','Inscripciones','▤'],['asistentes','Todos los asistentes','◎'],['autobus','Autobús','↗'],['vehiculos','Vehículos','▱'],['restauracion','Restauración','◇'],['necesidades','Necesidades especiales','♡'],['revision','Requieren revisión','!'],['documentos','Documentos','▧'],['valoracion','Valoración','☆'],['configuracion','Configuración','⚙']];
type Report={title:string;headers:string[];rows:string[][]};
const personHeaders=['Persona','Tipo','Edad','Transporte','Comida','Menú','Inscripción'];
const transport=(value?:string)=>value==='bus'?'Autobús':value==='car'?'Vehículo':'Por determinar';
function download(report:Report){const blob=new Blob([safeCsv([report.headers,...report.rows])],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`toledo-v2-${report.title.toLowerCase().replaceAll(' ','-')}.csv`;a.click();URL.revokeObjectURL(url);}
export default function Admin({area,username}:{area:string;username?:string}){
  const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const [query,setQuery]=useState('');const [age,setAge]=useState('all');const [menu,setMenu]=useState('all');const [direction,setDirection]=useState('asc');const [transportFilter,setTransportFilter]=useState('all');
  const [reports,setReports]=useState<Report[]>([]);const [selectedDocs,setSelectedDocs]=useState(['asistentes','autobus','vehiculos','restauracion']);
  async function api(action:string,payload?:unknown){const response=await fetch(`/api/admin/${action}`,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const value=await response.json() as Data & {error?:string};if(response.status===401){setData(null);window.location.assign('/admin/login');}if(!response.ok)throw new Error(value.error||'No se pudo completar la operación.');return value;}
  useEffect(()=>{if(area!=='login')api('data').then(setData).catch(e=>setError(e.message));},[area]); // Protected server endpoints are the authority.
  useEffect(()=>{if(!reports.length)return;const id=window.setTimeout(()=>window.print(),100);return()=>window.clearTimeout(id);},[reports]);
  useEffect(()=>{if(area==='login')return;let timer:ReturnType<typeof setTimeout>;const expire=()=>{setData(null);window.location.assign('/admin/login');};const reset=()=>{clearTimeout(timer);timer=setTimeout(expire,30*60*1000);};reset();window.addEventListener('pageshow',reset);return()=>{clearTimeout(timer);window.removeEventListener('pageshow',reset);};},[area,data]);
  const basePeople=useMemo(()=>{if(!data)return [];return data.people.filter(p=>area==='autobus'?p.transport==='bus':area==='restauracion'?p.meal:area==='necesidades'?Boolean(p.dietary||p.mobility):true);},[data,area]);
  const people=useMemo(()=>basePeople.filter(p=>(age==='all'||(age==='adult')===p.adult)&&(menu==='all'||p.menu===menu)&&(transportFilter==='all'||p.transport===transportFilter)&&`${p.name} ${p.registrationId} ${p.holderName}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,'es')*(direction==='asc'?1:-1)),[basePeople,age,menu,query,direction,transportFilter]);
  const title=sections.find(s=>s[0]===area)?.[1]||'Página no encontrada';
  function personReport(list:Data['people'],reportTitle=title,sensitive=false):Report{return {title:reportTitle,headers:[...personHeaders,...(sensitive?['Necesidad alimentaria','Movilidad']:[])],rows:list.map(p=>[p.name,p.role,p.adult?'Adulto':`Menor${p.age===undefined?' · sin edad':` · ${p.age} años`}`,transport(p.transport),p.meal?'Sí':'No',p.menu||'—',p.registrationId,...(sensitive?[p.dietary||'—',p.mobility||'—']:[])])};}
  function doc(key:string):Report{if(!data)return {title:'',headers:[],rows:[]};if(key==='vehiculos')return {title:'Vehículos',headers:['Titular','Modelo','Color','Matrícula','Ocupantes','Texto original'],rows:data.registrations.filter(r=>r.vehicle).map(r=>[r.holder.name,r.vehicle!.model||'Por revisar',r.vehicle!.color||'Por revisar',r.vehicle!.plate||'Por revisar',String(data.people.filter(p=>p.registrationId===r.id&&p.transport==='car').length),r.vehicle!.original])};if(key==='resumen')return {title:'Resumen operativo',headers:['Indicador','Total'],rows:[['Inscripciones',String(data.summary.registrations)],['Asistentes',String(data.summary.attendees)],['Autobús',String(data.summary.bus)],['Comensales',String(data.summary.diners)],['Pendientes de revisión',String(data.summary.pending)]]};return personReport(data.people.filter(p=>key==='autobus'?p.transport==='bus':key==='restauracion'?p.meal:key==='alimentarias'?Boolean(p.dietary):key==='movilidad'?Boolean(p.mobility):true),key==='alimentarias'?'Necesidades alimentarias':key==='movilidad'?'Necesidades de movilidad':sections.find(s=>s[0]===key)?.[1]||key,['alimentarias','movilidad'].includes(key));}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const value=await r.json() as {error?:string};if(!r.ok)throw new Error(value.error);window.location.assign('/admin');}catch(e){setError(e instanceof Error?e.message:'No se pudo conectar.');}finally{setBusy(false);}}
  async function refresh(){setBusy(true);setError('');try{setData(await api('refresh',{}));setNotice('Datos ficticios recalculados. No se ha consultado Google Sheets.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function logout(){const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok){setData(null);window.location.assign('/admin/login');}else setError('No se pudo cerrar la sesión. Inténtalo de nuevo.');}
  if(area==='login')return <main className="admin-login"><Link href="/">← Volver a la visita</Link><img src="/images/hero-wide-1600.png" alt="Toledo"/><section><span className="admin-eyebrow">CEMFAS · ORGANIZACIÓN</span><h1>Todo preparado.<br/>Todos juntos.</h1><p>Acceso privado a la organización de la visita.</p><form onSubmit={submit}><label>Usuario<input name="username" autoComplete="username" required maxLength={80}/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required maxLength={72}/></label>{error&&<p role="alert" className="admin-error">{error}</p>}<button disabled={busy}>{busy?'Comprobando…':'INICIAR SESIÓN'}</button></form><small>Sesión segura · Caducidad tras 30 minutos de inactividad</small></section></main>;
  const table=(report:Report)=><div className="admin-table-wrap"><table><thead><tr>{report.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table>{!report.rows.length&&<p className="admin-empty">No hay resultados con estos filtros.</p>}</div>;
  const stats=data?.summary;
  const pages=reports.flatMap(r=>Array.from({length:Math.max(1,Math.ceil(r.rows.length/20))},(_,i)=>({...r,rows:r.rows.slice(i*20,(i+1)*20)})));
  return <><main className="admin-shell"><aside><strong>TOLEDO</strong><p>Organización · V2</p><nav aria-label="Administración">{sections.map(([key,label,icon])=><Link key={key} href={key==='resumen'?'/admin':`/admin/${key}`} aria-current={area===key?'page':undefined}><span>{icon}</span>{label}{key==='revision'&&stats&&<b>{stats.pending}</b>}</Link>)}</nav><div className="admin-aside-footer"><Link href="/">← Ver zona pública</Link><small>{username}</small><button onClick={logout}>Cerrar sesión</button></div></aside><section className="admin-content"><header className="admin-header"><div><span className="admin-eyebrow">24 OCTUBRE 2026 · PROGRAMA PROVISIONAL</span><h1>{area==='resumen'?'Una visita, todo bajo control.':title}</h1><p>{area==='resumen'?'Personas, transporte y detalles. La organización empieza aquí.':'Visita cultural e institucional · CEMFAS'}</p></div><Link className="admin-public" href="/">Ver la visita ↗</Link></header><div className="admin-notice"><span>DEMOSTRACIÓN · DATOS FICTICIOS</span><span>Google Sheets sin conectar · IA opcional</span></div>{error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status" className="admin-success">{notice}</p>}{!data&&!error&&<p role="status">Cargando el panel seguro…</p>}
  {data&&stats&&<><div className="admin-update"><span>Última actualización: {new Date(data.updated).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})}</span><button disabled={busy} onClick={refresh}>{busy?'Actualizando…':'↻ Actualizar datos'}</button></div>
  {area==='resumen'&&<><div className="admin-metrics">{[[stats.attendees,'Personas en la visita',`${stats.adults} adultos · ${stats.minors} menores`],[stats.bus,'Plazas de autobús','Personas, no formularios'],[stats.diners,'Comensales',`${stats.adultMeals} adultos · ${stats.childMeals} menores`],[stats.pending,'Inscripciones por revisar','Aclarar antes de cerrar listados']].map(([n,label,detail],i)=><article className={i===0?'primary-metric':''} key={label}><span>{label}</span><strong>{n}</strong><small>{detail}</small></article>)}</div><div className="admin-two"><article className="admin-card"><span className="admin-eyebrow">ANTES DE LA VISITA</span><h2>Lo que necesita atención</h2>{data.issues.slice(0,4).map((issue,i)=><a className="admin-issue" key={i} href={`/admin/inscripciones?q=${issue.registrationId}`}><b>!</b><div><strong>{issue.reason}</strong><small>{issue.person} · {issue.registrationId}</small></div><span>→</span></a>)}<Link className="admin-text-link" href="/admin/revision">Ver todas las incidencias →</Link></article><article className="admin-card"><span className="admin-eyebrow">LA VISITA EN CIFRAS</span><h2>Cada persona cuenta</h2><dl className="admin-numbers">{[[stats.registrations,'Inscripciones'],[stats.holders,'Titulares'],[stats.companions,'Acompañantes'],[stats.car,'Personas en vehículo'],[stats.vehicles,'Vehículos'],[stats.dietary,'Necesidades alimentarias'],[stats.mobility,'Necesidades de movilidad']].map(([n,l])=><div key={l}><dt>{l}</dt><dd>{n}</dd></div>)}</dl></article></div><Link className="admin-document-callout" href="/admin/documentos"><div><strong>El dossier, listo para organizar.</strong><p>Selecciona solo los listados necesarios. Los datos sensibles quedan excluidos por defecto.</p></div><span>Preparar documentos →</span></Link></>}
  {['asistentes','autobus','restauracion','necesidades'].includes(area)&&<><div className="admin-section-lead"><strong>{area==='autobus'?`${stats.bus} plazas de autobús necesarias`:area==='restauracion'?`${stats.diners} comensales`:`${basePeople.length} personas`}</strong><p>{area==='autobus'?'La herencia del transporte de acompañantes es una regla provisional configurable.':area==='necesidades'?'Información restringida. No se incorpora automáticamente a los listados generales.':'Cada fila representa a una persona, asociada a su inscripción.'}</p></div>{area==='restauracion'&&<div className="admin-menu-counts">{Object.entries(stats.menus).map(([label,n])=><span key={label}>{label}<b>{n}</b></span>)}</div>}<div className="admin-filters"><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Persona o inscripción"/></label><label>Edad<select value={age} onChange={e=>setAge(e.target.value)}><option value="all">Todas</option><option value="adult">Adultos</option><option value="minor">Menores</option></select></label><label>Menú<select value={menu} onChange={e=>setMenu(e.target.value)}><option value="all">Todos</option>{[...new Set(basePeople.map(p=>p.menu))].map(m=><option value={m} key={m}>{m||'Sin menú'}</option>)}</select></label><label>Transporte<select value={transportFilter} onChange={e=>setTransportFilter(e.target.value)}><option value="all">Todos</option><option value="bus">Autobús</option><option value="car">Vehículo</option></select></label><label>Orden<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="asc">Nombre A–Z</option><option value="desc">Nombre Z–A</option></select></label></div><div className="admin-actions"><span>{people.length} resultados</span><button onClick={()=>download(personReport(people,title,area==='necesidades'))}>Exportar CSV filtrado</button><button onClick={()=>setReports([personReport(people,title,area==='necesidades')])}>Imprimir / PDF filtrado</button><button onClick={()=>setReports([personReport(basePeople,title,area==='necesidades')])}>Imprimir todo</button></div>{table(personReport(people,title,area==='necesidades'))}</>}
  {area==='inscripciones'&&<><label className="admin-search">Buscar inscripción<input defaultValue={typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('q')||''} onChange={e=>setQuery(e.target.value)} placeholder="DEMO-001 o nombre"/></label><div className="admin-registration-list">{data.registrations.filter(r=>`${r.id} ${r.holder.name}`.toLowerCase().includes((query||(typeof window!=='undefined'?new URLSearchParams(window.location.search).get('q')||'':'')).toLowerCase())).map(r=><article className="admin-card" key={r.id} id={r.id}><span className="admin-eyebrow">{r.id}</span><h2>{r.holder.name}</h2><p>{1+r.companions.length} personas · {transport(r.holder.transport)}</p><ul>{[r.holder,...r.companions].map(p=><li key={p.id}>{p.name} · {p.adult?'Adulto':'Menor'} · {p.meal?p.menu||'Menú pendiente':'No come'}</li>)}</ul><p className="admin-muted">Fuente: inscripción ficticia de demostración. La app no modifica las respuestas originales.</p></article>)}</div></>}
  {area==='vehiculos'&&<><div className="admin-section-lead"><strong>{stats.vehicles} vehículos · {stats.car} personas</strong><p>Se conserva el texto original. Los campos dudosos quedan pendientes de revisión.</p></div><div className="admin-actions"><button onClick={()=>download(doc('vehiculos'))}>Exportar CSV</button><button onClick={()=>setReports([doc('vehiculos')])}>Imprimir / PDF</button></div>{table(doc('vehiculos'))}</>}
  {area==='revision'&&<article className="admin-card"><h2>{data.issues.length} incidencias · {stats.pending} inscripciones</h2><p>Se señalan para revisión humana. No se corrigen ni descartan datos automáticamente.</p>{data.issues.map((issue,i)=><a className="admin-issue" key={i} href={`/admin/inscripciones?q=${issue.registrationId}`}><b>!</b><div><strong>{issue.reason}</strong><small>{issue.person} · {issue.registrationId}</small></div><span>Revisar →</span></a>)}{!data.issues.length&&<p>Sin incidencias detectadas.</p>}</article>}
  {area==='documentos'&&<article className="admin-card"><span className="admin-eyebrow">DOSSIER DE ORGANIZACIÓN</span><h2>Solo lo que necesitas compartir.</h2><p>Plantillas de impresión independientes del panel. En el diálogo de impresión puedes guardar como PDF.</p><div className="admin-doc-options">{[['resumen','Resumen operativo'],['asistentes','Listado general'],['autobus','Pasajeros del autobús'],['vehiculos','Relación de vehículos'],['restauracion','Listado nominal de menús'],['alimentarias','Necesidades alimentarias · restringido'],['movilidad','Necesidades de movilidad · restringido']].map(([key,label])=><label key={key}><input type="checkbox" checked={selectedDocs.includes(key)} onChange={e=>setSelectedDocs(v=>e.target.checked?[...v,key]:v.filter(x=>x!==key))}/><span>{label}</span><button onClick={()=>download(doc(key))}>CSV</button></label>)}</div><button disabled={!selectedDocs.length} onClick={()=>setReports(['resumen','asistentes','autobus','vehiculos','restauracion','alimentarias','movilidad'].filter(k=>selectedDocs.includes(k)).map(doc))}>Generar dossier · Imprimir / PDF</button><p className="admin-muted">Revisa el destinatario antes de incluir necesidades alimentarias o de movilidad.</p></article>}
  {area==='valoracion'&&<><div className="admin-metrics"><article className="primary-metric"><span>Respuestas ficticias</span><strong>{data.evaluations.length}</strong><small>Fuente independiente de las inscripciones</small></article><article><span>Valoración global</span><strong>{data.statistics.find(s=>s.question==='Global')?.mean?.toFixed(2)||'—'}<em>/ 5</em></strong><small>Media calculada sin IA</small></article><article><span>Participación</span><strong>—</strong><small>Sin censo de personas encuestables validado</small></article></div><div className="admin-two">{data.statistics.map(stat=><article className="admin-card" key={stat.question}><h2>{stat.question}</h2><p>N={stat.n} · Suma={stat.sum} · Media={stat.mean?.toFixed(2)||'—'} · Mediana={stat.median??'—'}</p>{stat.distribution.map(d=><div className="admin-bar" key={d.score}><span>{d.score} ★</span><meter min={0} max={100} value={d.percent} aria-label={`${d.score} estrellas: ${d.percent.toFixed(0)}%`}/><small>{d.count} · {d.percent.toFixed(0)}%</small></div>)}</article>)}</div><article className="admin-card"><h2>Comentarios originales</h2><label>Buscar comentarios<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar texto"/></label>{data.evaluations.filter(e=>e.comment.toLowerCase().includes(query.toLowerCase())).map(e=><blockquote key={e.id}>{e.comment}</blockquote>)}<div className="admin-actions"><button onClick={()=>download({title:'Comentarios',headers:['Referencia','Comentario original'],rows:data.evaluations.filter(e=>e.comment.toLowerCase().includes(query.toLowerCase())).map(e=>[e.id,e.comment])})}>Exportar comentarios filtrados</button><button onClick={()=>setReports([{title:'Resultados de valoración · sin IA',headers:['Pregunta','N','Suma','Media','Mediana'],rows:data.statistics.map(s=>[s.question,String(s.n),String(s.sum),s.mean?.toFixed(2)||'—',String(s.median??'—')])},{title:'Comentarios originales',headers:['Referencia','Comentario'],rows:data.evaluations.filter(e=>e.comment.toLowerCase().includes(query.toLowerCase())).map(e=>[e.id,e.comment])}])}>Informe de resultados / PDF</button></div></article><article className="admin-card admin-ai"><span className="admin-eyebrow">ANÁLISIS MEDIANTE IA · OPCIONAL</span><h2>La interpretación, cuando tú decidas.</h2><p>No se ha enviado ningún comentario a un proveedor de IA. Las estadísticas anteriores se calculan mediante código.</p><button onClick={()=>setNotice('IA sin configurar. El adaptador exige comentarios previamente anonimizados y verificados antes de permitir un envío.')}>Analizar comentarios</button></article></>}
  {area==='configuracion'&&<article className="admin-card"><h2>Configuración de la actividad</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{setData(await api('settings',{evaluationActive:form.has('evaluationActive'),inheritTransport:form.has('inheritTransport')}));setNotice('Configuración guardada en el servidor.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label className="admin-check"><input type="checkbox" name="evaluationActive" defaultChecked={data.settings.evaluationActive}/>Mostrar encuesta de valoración en la zona pública</label><label className="admin-check"><input type="checkbox" name="inheritTransport" defaultChecked={data.settings.inheritTransport}/>Los acompañantes heredan el transporte del titular si no tienen transporte propio declarado</label><button disabled={busy}>Guardar configuración</button></form><hr/><dl className="admin-numbers"><div><dt>Google Sheets</dt><dd>Sin conectar</dd></div><div><dt>Inteligencia artificial</dt><dd>No configurada</dd></div><div><dt>Autenticación</dt><dd>Servidor · bcrypt · sesión privada</dd></div><div><dt>Caducidad por inactividad</dt><dd>30 minutos</dd></div></dl><p className="admin-muted">Las credenciales se configuran fuera del código. No se muestran ni se solicitan en este panel.</p></article>}
  {!sections.some(s=>s[0]===area)&&<Link href="/admin">Volver al resumen</Link>}
  </>}</section></main><section className="admin-print" aria-hidden={!reports.length}>{pages.map((page,i)=><article className="admin-print-page" key={i}><header><strong>VISITA A TOLEDO 2026</strong><h1>{page.title}</h1><p>DEMOSTRACIÓN · DATOS FICTICIOS · Datos actualizados a: {data?new Date(data.updated).toLocaleString('es-ES'):''}</p></header><table><thead><tr>{page.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{page.rows.map((r,j)=><tr key={j}>{r.map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table><footer>Generado: {new Date().toLocaleDateString('es-ES')} · Uso organizativo · Página {i+1} de {pages.length}</footer></article>)}</section></>;
}
