import test from 'node:test';
import assert from 'node:assert/strict';
import {registrationsFromGoogle} from '../server/google-mapping.ts';
import {googleSources} from '../server/google-schema.ts';
import {makeSnapshot} from '../server/snapshot.ts';
import {validateHeaders} from '../server/google-columns.ts';
const headers:string[]=[...googleSources.registrations.headers];headers[47]='NECESIDAD ALIMENTARIA ESPECIAL';headers[48]='INDIQUE LA PERSONA Y DETALLE LA ALERGIA, INTOLERANCIA U OTRA NECESIDAD ALIMENTARIA';
for(const course of ['PRIMER','SEGUNDO'])for(let i=0;i<7;i++)headers.push(`${course} PLATO — MENÚ GENERAL (MENÚ 6) — POR PERSONA [${i?`Acompañante ${i}`:'Titular'}]`);
function row(changes:Record<number,string>={}){const cells=Array<string>(headers.length).fill('');Object.assign(cells,{0:'7/10/2026',1:'Persona ficticia',4:'SI',5:'SI',7:'NO',37:'NO',40:'Adulto - Menú general (Menú 6)',47:'No',51:'Confirmado',52:'Confirmado',53:'Confirmado',55:'Garbanzos con almejas',62:'Costillas BBQ',...changes});return {rowNumber:2,headers,cells};}
const snapshot=(r:ReturnType<typeof row>)=>makeSnapshot(registrationsFromGoogle([r]),[],true,'google','now');
test('Menú 6 conserva nombres y platos tras insertar y mover columnas',()=>{const r=row();const indexes=headers.map((_,i)=>i);indexes.unshift(indexes.splice(62,1)[0]);const moved={...r,headers:['Campo nuevo',...indexes.map(i=>headers[i])],cells:['ignorado',...indexes.map(i=>r.cells[i])]};assert.deepEqual(snapshot(moved).registrations,snapshot(r).registrations);assert.equal(snapshot(r).summary.firstCourses['Garbanzos con almejas'],1);});
test('platos incompletos, desconocidos, no comensales e infantiles generan revisión sin bloquear',()=>{assert(snapshot(row({55:'',62:''})).issues.some(i=>i.reason.includes('sin primer')));assert(snapshot(row({62:'Desconocido'})).issues.some(i=>i.reason.includes('desconocido')));assert(snapshot(row({40:'No solicita menú'})).issues.some(i=>i.reason.includes('incompatible')));const child=snapshot(row({40:'Infantil - Normal',55:'',62:''}));assert(!child.issues.some(i=>i.reason.includes('sin primer')));assert(snapshot(row({40:''})).issues.some(i=>i.reason.includes('sin menú')));});
test('tipos especiales se separan por inscripción y conservan detalle literal sin atribución automática',()=>{for(const type of ['Vegetariano','Vegano','Halal','Alergia/intolerancia','Otro']){const d=snapshot(row({47:type,48:'  Persona: texto original\nSin modificar  ',49:' Medidas originales '}));assert.equal(d.summary.specialNeeds[type],1);assert.equal(d.registrations[0].groupNeeds?.dietaryDetail,'  Persona: texto original\nSin modificar  ');assert.equal(d.people[0].dietary,undefined);assert.equal(d.summary.specialNeeds[type==='Halal'?'Vegano':'Halal'],0);}});
test('detalle requerido solo para alergia/intolerancia y otro; contradicciones requieren revisión',()=>{for(const type of ['Alergia/intolerancia','Otro'])assert(snapshot(row({47:type})).issues.some(i=>i.reason.includes('sin detalle requerido')));assert(!snapshot(row({47:'Vegetariano'})).issues.some(i=>i.reason.includes('sin detalle requerido')));assert(snapshot(row({47:'Vegetariano'})).issues.some(i=>i.reason.includes('compatibilidad')));assert(snapshot(row({47:'No',48:'Texto'})).issues.some(i=>i.reason.includes('No con detalle')));});
test('cabeceras ausentes y platos duplicados se rechazan; histórico sigue disponible',()=>{assert.throws(()=>validateHeaders('registrations',headers.filter(h=>h!=='Marca temporal')));const r=row();assert.throws(()=>snapshot({...r,headers:[...headers,headers[55]],cells:[...r.cells,'']}));const historic={...r,headers:[...googleSources.registrations.headers],cells:r.cells.slice(0,55)};assert.equal(snapshot(historic).people.length,1);assert.equal(snapshot(historic).people[0].courseSchema,false);});
