export type Person = {id:string;name:string;role:'Titular'|'Acompañante';adult:boolean;age?:number;transport?:'bus'|'car';meal:boolean;menu:string;dietary?:string;mobility?:string};
export type Registration = {id:string;holder:Person;companions:Person[];vehicle?:{model:string;color:string;plate:string;original:string};declaredMeals?:number};
export type Attendee = Person & {registrationId:string;holderName:string;inheritedTransport:boolean};
export type Evaluation = {id:string;scores:Record<string,number|null>;comment:string};
export type Incident = {registrationId:string;person:string;reason:string};
export function normalize(registrations:Registration[],inheritTransport=true):Attendee[]{return registrations.flatMap(r=>[r.holder,...r.companions].map(p=>({...p,registrationId:r.id,holderName:r.holder.name,transport:p.transport || (inheritTransport?r.holder.transport:undefined),inheritedTransport:!p.transport&&inheritTransport})));}
export function review(registrations:Registration[],people:Attendee[]):Incident[]{
  const issues:Incident[]=[];const add=(p:Attendee,reason:string)=>issues.push({registrationId:p.registrationId,person:p.name||'Sin nombre',reason});
  const names=new Map<string,string>();
  for(const p of people){if(!p.name.trim())add(p,'Persona incompleta: falta nombre');if(!p.adult&&p.age===undefined)add(p,'Menor sin edad');if(p.age!==undefined&&(p.age<0||p.age>120||(p.adult?p.age<18:p.age>=18)))add(p,'Edad incompatible con adulto/menor');if(p.meal&&!p.menu)add(p,'Comensal sin menú');if(!p.meal&&p.menu)add(p,'Menú asignado a una persona que no come');if(!p.transport)add(p,'Transporte sin determinar');const name=p.name.trim().toLocaleLowerCase('es');if(name&&names.has(name))add(p,`Posible duplicado con ${names.get(name)}`);if(name)names.set(name,p.registrationId);}
  for(const r of registrations){const group=people.filter(p=>p.registrationId===r.id);if(group.some(p=>p.transport==='car')&&(!r.vehicle?.model||!r.vehicle?.plate||!r.vehicle?.color))issues.push({registrationId:r.id,person:r.holder.name,reason:'Vehículo con información incompleta'});if(r.vehicle&&group.every(p=>p.transport==='bus'))issues.push({registrationId:r.id,person:r.holder.name,reason:'Vehículo declarado pero todos viajan en autobús'});if(r.declaredMeals!==undefined&&r.declaredMeals!==group.filter(p=>p.meal).length)issues.push({registrationId:r.id,person:r.holder.name,reason:'Número declarado de menús distinto al de comensales'});}
  return issues;
}
export function summarize(registrations:Registration[],people:Attendee[],issues:Incident[]){
  const menus:Record<string,number>={};for(const p of people.filter(p=>p.meal)){const key=`${p.adult?'Adulto':'Menor'} · ${p.menu||'Sin elegir'}`;menus[key]=(menus[key]||0)+1;}
  return {registrations:registrations.length,attendees:people.length,holders:people.filter(p=>p.role==='Titular').length,companions:people.filter(p=>p.role==='Acompañante').length,adults:people.filter(p=>p.adult).length,minors:people.filter(p=>!p.adult).length,bus:people.filter(p=>p.transport==='bus').length,car:people.filter(p=>p.transport==='car').length,vehicles:registrations.filter(r=>r.vehicle).length,diners:people.filter(p=>p.meal).length,adultMeals:people.filter(p=>p.meal&&p.adult).length,childMeals:people.filter(p=>p.meal&&!p.adult).length,dietary:people.filter(p=>p.dietary).length,mobility:people.filter(p=>p.mobility).length,pending:new Set(issues.map(i=>i.registrationId)).size,menus};
}
export function statistics(evaluations:Evaluation[]){const keys=[...new Set(evaluations.flatMap(e=>Object.keys(e.scores)))];return keys.map(question=>{const values=evaluations.map(e=>e.scores[question]).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v)&&Number.isInteger(v)&&v>=1&&v<=5).sort((a,b)=>a-b);const n=values.length;const sum=values.reduce((a,b)=>a+b,0);const middle=Math.floor(n/2);return {question,n,sum,mean:n?sum/n:null,median:n?(n%2?values[middle]:(values[middle-1]+values[middle])/2):null,distribution:[1,2,3,4,5].map(score=>({score,count:values.filter(v=>v===score).length,percent:n?values.filter(v=>v===score).length/n*100:0}))};});}
export function safeCsv(rows:unknown[][]){return '\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(';')).join('\r\n');}
