// Verified against Google Sheets headers and Forms options on 2026-08-31.
// Only schema/configuration: never put response data or credentials here.
export const googleSources = {
  registrations: {id: '15J__XQ8jXRFS8IjLxroA4gXjhoqe3MarfjVDOA8oRpQ', sheetId: 1532620971, tab: 'Respuestas de formulario 1', lastColumn: 'BC', headers: ["Marca temporal","NOMBRE Y APELLIDOS","EMPLEO","IDENTIFIQUE A SU PADRINO/APADRINADO (Solo para alumnos)","¿DESEA ASISTIR A LA COMIDA DE CONFRATERNIZACIÓN ORGANIZADA POR LA ESFAS? (El importe del menú será abonado personalmente)","¿DESEA EMPLEAR EL AUTOBÚS PROPORCIONADO POR LA ORGANIZACIÓN?","INDIQUE EL MODELO, COLOR Y MATRÍCULA DEL VEHÍCULO CON EL QUE ASISTIRÁ","¿ASISTIRÁ CON ACOMPAÑANTES?","NOMBRE Y APELLIDOS","RELACIÓN CON EL TITULAR","¿ES ADULTO O MENOR DE EDAD?","EDAD DEL MENOR","¿DESEA AÑADIR OTRO ACOMPAÑANTE?","NOMBRE Y APELLIDOS","RELACIÓN CON EL TITULAR","¿ES ADULTO O MENOR DE EDAD?","EDAD DEL MENOR","¿DESEA AÑADIR OTRO ACOMPAÑANTE?","NOMBRE Y APELLIDOS","RELACIÓN CON EL TITULAR","¿ES ADULTO O MENOR DE EDAD?","EDAD DEL MENOR","¿DESEA AÑADIR OTRO ACOMPAÑANTE?","NOMBRE Y APELLIDOS","RELACIÓN CON EL TITULAR","¿ES ADULTO O MENOR DE EDAD?","EDAD DEL MENOR","¿DESEA AÑADIR OTRO ACOMPAÑANTE?","NOMBRE Y APELLIDOS","RELACIÓN CON EL TITULAR","¿ES ADULTO O MENOR DE EDAD?","EDAD DEL MENOR","¿DESEA AÑADIR OTRO ACOMPAÑANTE?","NOMBRE Y APELLIDOS","RELACIÓN CON EL TITULAR","¿ES ADULTO O MENOR DE EDAD?","EDAD DEL MENOR","¿ALGUNO DE LOS ASISTENTES PRESENTA ALGUNA NECESIDAD O LIMITACIÓN DE MOVILIDAD QUE DEBA TENERSE EN CUENTA PARA ORGANIZAR LA ACTIVIDAD?","INDIQUE LA PERSONA AFECTADA Y DESCRIBA LA NECESIDAD DE APOYO","TRATAMIENTO DE INFORMACIÓN SOBRE NECESIDADES DE MOVILIDAD","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Titular]","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Acompañante 1]","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Acompañante 2]","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Acompañante 3]","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Acompañante 4]","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Acompañante 5]","INDIQUE EL MENÚ SOLICITADO POR CADA ASISTENTE [Acompañante 6]","¿ALGUNO DE LOS ASISTENTES PRESENTA ALGUNA ALERGIA O INTOLERANCIA ALIMENTARIA?","INDIQUE EL NOMBRE DE LA PERSONA AFECTADA Y LA ALERGIA O INTOLERANCIA.","OBSERVACIONES O MEDIDAS ALIMENTARIAS NECESARIAS.","TRATAMIENTO DE INFORMACIÓN SOBRE ALERGIAS E INTOLERANCIAS","CONFIRMACIÓN DE LOS DATOS","DATOS DE ACOMPAÑANTES Y MENORES"," INFORMACIÓN SOBRE PROTECCIÓN DE DATOS","Dirección de correo electrónico"]},
  evaluations: {id: '1bGUu3Xb51lnC5vyZC6dsCN-7A-lDh6GZ2n4Lo7dS-WI', sheetId: 151133299, tab: 'Respuestas de formulario 1', lastColumn: 'P', headers: ["Marca temporal","¿Cómo valorarías globalmente la actividad?","¿En qué medida te ha resultado interesante la visita cultural a Toledo?","¿En qué medida consideras que la actividad te ha ayudado a conocer mejor la historia, cultura y patrimonio de España?","¿Cómo valorarías la visita a la Academia de Infantería?","¿Cómo valorarías la organización general de la actividad?","¿La información recibida antes de la actividad fue suficiente y clara?","¿Cómo valorarías la organización del transporte?","¿Cómo valorarías la comida de confraternización?","Duración de la actividad","Ritmo de la actividad.","¿Qué parte de la actividad te ha resultado más interesante?","¿Qué aspecto de la actividad mejorarías?","¿Qué recomendarías mantener, modificar o añadir en futuras ediciones?","¿Consideras que este tipo de actividades favorece la relación entre alumnos aliados y sus padrinos?","¿Recomendarías mantener esta actividad en futuras ediciones del CEMFAS?"]},
} as const;
export const menuOptions = ['No solicita menú', 'Adulto - Normal', 'Adulto - Vegetariano', 'Adulto - Vegano', 'Adulto - Halal', 'Infantil - Normal', 'Infantil - Vegetariano', 'Infantil - Vegano', 'Infantil - Halal'];
export const surveyLabels = ['Global', 'Visita cultural', 'Historia y patrimonio', 'Academia de Infantería', 'Organización', 'Información previa', 'Transporte', 'Comida'];
export const choiceOptions = {
  Duración: ['Demasiado corta.', 'Adecuada.', 'Demasiado larga.'],
  Ritmo: ['Demasiado lento.', 'Adecuado.', 'Demasiado intenso.'],
  Recomendación: ['SI', 'Si pero con cambios sustanciales', 'No'],
};
