import type {Registration,Evaluation,Person} from './domain';
const person=(id:string,name:string,role:Person['role'],adult=true,menu='Arroz con verduras',extra:Partial<Person>={}):Person=>({id,name,role,adult,meal:true,menu,...extra});
export const registrations:Registration[]=[
 {id:'DEMO-001',holder:person('1','Familia Demo Uno · titular','Titular',true,'Arroz con verduras',{transport:'bus'}),companions:[person('2','Familia Demo Uno · acompañante','Acompañante'),person('3','Familia Demo Uno · menor','Acompañante',false,'Macarrones',{age:9})],declaredMeals:3},
 {id:'DEMO-002',holder:person('4','Familia Demo Dos · titular','Titular',true,'Pescado',{transport:'car'}),companions:[person('5','Familia Demo Dos · acompañante','Acompañante',true,'Vegetariano',{dietary:'Ejemplo ficticio: sin frutos secos'})],vehicle:{model:'Vehículo de ejemplo',color:'Azul',plate:'DEMO-02',original:'Vehículo de ejemplo, azul, DEMO-02'},declaredMeals:2},
 {id:'DEMO-003',holder:person('6','Familia Demo Tres · titular','Titular',true,'Arroz con verduras',{transport:'bus',mobility:'Ejemplo ficticio: evitar escaleras'}),companions:[person('7','Familia Demo Tres · menor','Acompañante',false,'')],declaredMeals:2},
 {id:'DEMO-004',holder:person('8','Participante Demo Cuatro','Titular',true,'',{transport:'car',meal:false}),companions:[],vehicle:{model:'',color:'',plate:'',original:'Texto de vehículo pendiente de aclaración'},declaredMeals:0},
 {id:'DEMO-005',holder:person('9','Familia Demo Cinco · titular','Titular',true,'Vegetariano',{transport:'bus'}),companions:[person('10','Familia Demo Cinco · acompañante','Acompañante',true,'Pescado'),person('11','Familia Demo Cinco · menor','Acompañante',false,'Macarrones',{age:12})],declaredMeals:3},
 {id:'DEMO-006',holder:person('12','Participante Demo Seis','Titular',true,'Arroz con verduras',{transport:'bus'}),companions:[],declaredMeals:1}
];
export const evaluations:Evaluation[]=[{id:'EV-01',scores:{Global:5,Recorrido:5,Organización:4},comment:'Ejemplo ficticio: la guía ayudó a comprender la ciudad.'},{id:'EV-02',scores:{Global:4,Recorrido:5,Organización:4},comment:'Ejemplo ficticio: habría agradecido una pausa más larga.'},{id:'EV-03',scores:{Global:5,Recorrido:4,Organización:5},comment:'Ejemplo ficticio: la comida facilitó conocer a otras familias.'},{id:'EV-04',scores:{Global:3,Recorrido:4,Organización:3},comment:'Ejemplo ficticio: convendría aclarar el punto de encuentro.'}];
